# Generated by Django 5.2.7 on 2025-10-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appcatalog',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='linkedapp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='linkedapp',
            name='username',
        ),
        migrations.AddField(
            model_name='appcatalog',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appcatalog',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='linkedapp',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_users', to='core.appcatalog'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
