# Generated by Django 5.2.7 on 2025-10-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userpreference_user_remove_appcatalog_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcatalog',
            name='reference',
            field=models.CharField(max_length=200),
        ),
    ]
