# Generated by Django 5.2.7 on 2025-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appcatalog_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedapp',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
